parserOptions:
    root: true
    ecmaVersion: 5
    sourceType: "script"
    ecmaFeatures:
        jsx: true
    rules:
        max-len: [2, 120, 4]

        # stylistic
        func-names: 2
        indent: [2, 4, {"SwitchCase": 1}]
        quotes: [2, "single"]
        quote-props: [2, "always"]
        semi: [2, "always"]


    plugins: ["react"]

    extends: "google"

    env:
        browser: true
        jquery: true
