#! /bin/bash


ln -s $HOME/dotfiles/.linux $HOME/.linux

cd $HOME
if [ ! -d "$HOME/.config" ]; then
    mkdir "$HOME/.config"
fi
if [ -a "$HOME/.zshrc" ]; then
    mv .zshrc .zshrc.orig
fi
if [ -a "$HOME/.vimrc" ]; then
    mv .vimrc .vimrc.orig
fi
if [ -a "$HOME/.gitconfig" ]; then
    mv .gitconfig .gitconfig.orig
fi

curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

mkdir $HOME/bin
ln -s $HOME/dotfiles/.ackrc
ln -s $HOME/dotfiles/.default-difftool.sh $HOME/bin/default-difftool.sh
ln -s $HOME/dotfiles/.gitconfig
ln -s $HOME/dotfiles/.tmux.conf
ln -s $HOME/dotfiles/.vim
ln -s $HOME/dotfiles/.vimrc
ln -s $HOME/dotfiles/.zshrc
ln -s $HOME/dotfiles/angular-vim-snippets/UltiSnips $HOME/dotfiles/.vim/UltiSnipsAngular
ln -s $HOME/dotfiles/.config/powerline $HOME/.config/powerline

