#! /bin/bash
PLATFORM=`uname`

if !hash stow 2>/dev/null; then
    echo The stow command seems to be missing, please install that before proceeding
    exit
fi

function build_vim {
    # roll our own VIM
    case $PLATFORM in
        SunOS)
            sudo pkgin -y install mercurial
            sudo pkgin -y install build-essential
            sudo pkgin -y install cmake
            ;;
        Linux)
            sudo apt-get -y install libncurses5-dev python-dev mercurial
            sudo apt-get -y install cmake
            sudo apt-get -y remove vim vim-runtime gvim vim-tiny vim-common vim-gui-common
            ;;
    esac

    cd ~
    git clone https://github.com/vim/vim.git
    cd vim
    git checkout v8.0.0325
    case $PLATFORM in
        SunOS)
            ./configure --with-features=huge \
                --enable-rubyinterp \
                --enable-pythoninterp \
                --enable-cscope --prefix=/opt/local
            make VIMRUNTIMEDIR=/opt/local/share/vim/vim80
            sudo make install
            ;;
        Linux)
            ./configure --with-features=huge \
                --enable-rubyinterp \
                --enable-pythoninterp \
                --enable-perlinterp \
                --enable-cscope --prefix=/usr
            make VIMRUNTIMEDIR=/usr/share/vim/vim80
            sudo make install
            sudo update-alternatives --install /usr/bin/editor editor /usr/bin/vim 1
            sudo update-alternatives --set editor /usr/bin/vim
            sudo update-alternatives --install /usr/bin/vi vi /usr/bin/vim 1
            sudo update-alternatives --set vi /usr/bin/vim
            ;;
    esac
}

case $PLATFORM in
    Darwin)
        brew install cmake reattach-to-user-namespace
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
        ~/.fzf/install
        ;;
    SunOS)
        sudo pkgin -y install zsh
        sudo pkgin -y install tmux
        sudo usermod -s /opt/local/bin/zsh $USER
        ln -s $HOME/dotfiles/.sun $HOME/.sun
        build_vim
        ;;
    Linux)
        sudo apt-get -y install zsh
        sudo chsh -s /usr/bin/zsh $USER
        sudo apt-get -y install curl
        ln -s $HOME/dotfiles/.linux $HOME/.linux
        build_vim
        ;;
esac

cd $HOME/dotfiles
git submodule update --init --recursive
curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
ln -s ~/dotfiles/rickyn.zsh-theme ~/.oh-my-zsh/themes/rickyn.zsh-theme

stow config
stow emacs
stow git
stow i3
stow pt
stow tmux
stow vim
stow weechat
stow zsh

