#! /bin/sh
PWD=`pwd`
git pull origin master

# in case there are new modules
git submodule init
#git submodule update
git submodule update --init --recursive

# update any existing modules
git submodule foreach git pull origin master
cd .vim/bundle/YouCompleteMe
git submodule update --init --recursive
./install.sh
cd "$PWD"
