#! /bin/sh
PWD=`pwd`
git pull origin master

# in case there are new modules
git submodule init
git submodule update

# update any existing modules
git submodule foreach git pull origin master
cd .vim/bundle/YouCompleteMe
./install.sh
cd ../tern_for_vim
npm install
cd "$PWD"
