# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Auto-mount removable media (USB drives, DVDs, etc.)
exec-once = udiskie -an
exec-once = ckb-next --background

# Disable the trackpad while an external mouse is plugged in
exec-once = ~/.local/bin/touchpad-auto-toggle
