theme = "dracula"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
clickable = false
icons = false
display_type = "memory"
format_mem = "\uf0a0 {mem_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "custom"
interval = 10
command = "echo '\uf1eb' `ip -br addr show dev eno1 | awk '{ print $3}'`"
#command = "echo '\uf1eb' `ip -br addr show dev enxf8e43b5820f0 | awk '{ print $3}'`"

[[block]]
block = "time"
interval = 5
format = "%a %Y-%m-%d %R"

